[package]
name = "bf"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
ctrlc = "3.4.7"
thiserror = "2.0.16"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
